# -*- coding: utf-8 -*-
"""project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WH_84lVwcdKKzQSIfZgUwbIwjSFD6EHU
"""

import pandas as pd
data=pd.read_csv('/content/tips.csv')
print(data)

import matplotlib.pyplot as plt
import pandas as pd
data=pd.read_csv('/content/tips.csv')

plt.hist(data[day],color=blue,alpha=0.7)
plt.xlabel(&#39;day&#39;)
plt.ylabel(&#39;Frequency&#39;)
plt.title(&#39;histplot&#39;)
plt.show()